adminUser:
  password: vault:jx-aps-pr-210-17arc/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-pr-210-17arc:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-pr-210-17arc:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-pr-210-17arc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-pr-210-17arc/prow:hmacToken
